### ISSUE TITLE
TemplatePlaceholderReplaceUtil class Bug

### ISSUE THREAD

**Issue by mjozefow** [ConnectForLife/openmrs-module-sms#1]
Hi, I have encountered an issue with SMS provider parameter, usage of Pattern while creating template without parameter. When i configure template to Resolve JSON arrays from iterable parameter values, and if I set no parameter into array, system anyway wants to resolve square brackets [] as if they contain it. I think it should work like that: if I am not passing any parameter inside [] system should ignore square brackets. Then it match properly to [pattern_name] pattern.

**Comment by pwargulak** [comment]
Hi, 
We have integrated your PR into our internal repo, your fix will be included in the next release of omrs-sms module source code. 
Just for future reference, our internal PR id: omrs-sms#13.
